### ISSUE TITLE
crypto-square: rename getSquareSize()

### ISSUE THREAD

**Issue by rstockbridge** [exercism/java#1107]
The method `getSquareSize()` in CryptoSquareTest.java is confusingly named because the characters usually form a rectangle, not a square. I deduced that `getSquareSize()` is looking for the number of columns in the rectangle.

What do you think of renaming `getSquareSize()` to something like `getNumberOfColumns()`?

**Comment by FridaTveit** [comment]
I agree that is confusing, thanks for bringing it to our attention @rstockbridge! :)

Actually the tests for crypto-square are very different from the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json). The canonical data only tests the encryption method. I'd suggest changing our tests and example implementation to comply with the canonical data, then we'd completely get rid of the confusing method. What do you think @rstockbridge, @exercism/java? :)

**Comment by sjwarner-bp** [comment]
I think that it would be a great idea to more closely mirror the canonical data 🙂

**Comment by rstockbridge** [comment]
Sounds good to me!

**Comment by stkent** [comment]
+1 to the update. Reminder that there's a handy script (https://github.com/exercism/java/blob/master/scripts/canonical_data_check.sh) that can be run locally along with an updated copy of `problem-specifications` in order to easily see which exercises are out-of-date, if there's enthusiasm for proactively bringing these kinds of improvements to the Java tracK!

**Comment by sjwarner-bp** [comment]
Closed via #1178
