### ISSUE TITLE
exercises: Write comments

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [exercism/java#1118]
Some of the code for model answers are long and may be hard to understand. Some header comments describing the general algorithm will be helpful in understanding what the code is doing.

Also, as part of adhering to best practices of programming, we also should minimally write a few lines of header comments for each method in the model answer.

**Comment by FridaTveit** [comment]
Hi @Zhiyuan-Amos, thanks for raising this issue. The reference solutions aren't meant to be model answers. They aren't shown to the users, they're just used for us to check that the tests work and that it is possible to implement a solution. We normally try to adhere to best practices and write good code in the reference solutions, but they don't have to necessarily be the best possible solution to the exercise.

Also, since they aren't meant to be viewed by people solving the problem and they all deal with relatively small exercises, I don't think it's necessary to clutter them with header comments.

So if you find any specific examples of things that can be improved in the reference solutions, feel free to open an issue or a pull request for it (though please only fix/raise one thing per PR/issue). But I don't think any major change is needed :) What do you think @Zhiyuan-Amos, @exercism/java?

**Comment by sjwarner-bp** [comment]
I'd be inclined to agree with you @FridaTveit - as these aren't really 'user-facing', they don't need to spell out exactly how the solution has been implemented, and may be a fair amount of clutter (especially if reference solutions are updated with test suites).

While obviously we should adhere to good practises, I'm sure I have read (maybe in a different exercism repo, but I imagine the same applies here) that reference solutions don't need to be optimal, as long as they are sensible 🙂

**Comment by FridaTveit** [comment]
The general Exercism [implement a new exercise guide](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#the-reference-solution) explains what is expected of a reference solution:
> The solution does not need to be particularly great code, it is only used to verify that the exercise is coherent.

:)

**Comment by Zhiyuan-Amos** [comment]
Thank you for both of your comments and for referring me to the Exercism doc :)
