### ISSUE TITLE
RNA Transcription: exceptions not mentioned in README

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1208]
A recent issue in [exercism.io/#3705](https://github.com/exercism/exercism.io/issues/3705) has pointed out that we don't mention when exceptions are expected in exercise solutions.

I've briefly made an explanation of why this is the case in the issue, but I was wondering what others thought about it.

I think that the fact exceptions are expected in the tests should indicate to users that this is how their program should behave. Additionally, this kind of workflow matches with TDD, where you should write methods to pass tests that have already been written.

However, if we decide to describe exceptions in READMEs, the circumstances could be documented in POLICIES, and relevant HINTS could be added.

Let me know what you think @exercism/java 🙂

**Comment by FridaTveit** [comment]
We've added a hint to the [hamming exercise](https://github.com/exercism/java/blob/master/exercises/hamming/.meta/hints.md) since that was (at least at some point) the first exercise using exceptions. I guess this is a similar problem to the starter implementation hints. We could add  the hint to any always available exercises which use exceptions (rna-transcription is always available, i.e. it is not unlocked by anything) or we could add it to all exercises using exceptions? What do you think? 🙂

**Comment by sjwarner-bp** [comment]
I think adding it to all exercises might be overkill, but I like the idea of adding it to all always available exercises! :slightly_smiling_face:

**Comment by FridaTveit** [comment]
It looks like the only always available exercise which uses exceptions is rna-transcription, so we only need to add the hint to that exercise. And I think we should also add `exception_handling` to the topics for rna-transcription 🙂

**Comment by FridaTveit** [comment]
Actually, I just checked the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/canonical-data.json) for rna-transcription, and the test cases that required an exception to be thrown have been removed! So I suggest we close this issue and instead update the tests as per #1122 😆

**Comment by sjwarner-bp** [comment]
I didn't realise! Thanks for checking that out @FridaTveit - that sounds like the best course of action :slightly_smiling_face:
