### ISSUE TITLE
Code Freeze?

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1328]
I've just checked out the [Gitter channel](https://gitter.im/exercism/support), and according to a post there the Java track is a code freeze for this repo until v2 launches? The post was on 20th Feb at 15:13.

> there is a code freeze for that repository, unless there are blocking bugs, it is unlikely that anything will happen on that repository before V2.

I feel like I might have missed something here, as I didn't see anything about this before. Is there somewhere that lists this kind of info / are the rest of you aware of this @exercism/java ?

**Comment by Smarticles101** [comment]
I think NobbZ was referring to the exercism.io repository in his response. That is where jhuiet linked to in the previous message. Since the v2 prototype is in a private repository right now and the development is focused on that, there isn't going to be any changes to the current codebase for the site unless they fix breaking bugs

**Comment by sjwarner-bp** [comment]
Ok, that makes way more sense - I thought I might be reading that message thread wrong! 😉

Thanks for reassuring me that I'd not missed out on something major here! I'll close this ☺️
