### ISSUE TITLE
rectangles: update version file (1.0.0 -> 1.1.0) and add test

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1372]
Please update the version specified in the [rectangles](https://github.com/exercism/java/blob/master/exercises/rectangles/.meta/version) version file from 1.0.0 to 1.1.0.

Also please add the second test in the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rectangles/canonical-data.json) which is missing from [our tests](https://github.com/exercism/java/blob/master/exercises/rectangles/src/test/java/RectangleCounterTest.java). This test should be exactly the same as the first test except that the input grid should be an array with one empty string (`new String[]{""}`) instead of an empty array of strings (`new String[]{}`).

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/rectangles/canonical-data.json).

**Comment by tendaitt** [comment]
I noticed that there might be a naming error in the [tests](https://github.com/exercism/java/blob/master/exercises/rectangles/src/test/java/RectangleCounterTest.java).

According to the canonical data, the first test actually tests if no rows results in no rectangles but its name in the test file is `testInputWithNoColumnsContainsNoRectangles` instead of `testInputWithNoRowsContainsNoRectangles`.

The test that I am adding (`new String[]{""}`) is actually the `testInputWithNoColumnsContainsNoRectangles`. Should I fix this in this issue?
