### ISSUE TITLE
go-counting:tests

### ISSUE THREAD

**Issue by jhuiet** [exercism/java#1395]
Short explanation of easy fix:
Change the tests according to the //comments made below.
Edit the readme so that it includes a descriptor notifying that the edges count as sides.

The tests for the current 'go' exercise don't seem to follow the rules I have found on how go should be played. The main grief I had are two particular tests(posted below). from what I can tell the space between two BLACK pieces and two WHITE pieces is a draw, and not black OR white (therefore it would be none), and the area on the corners would be a territory for whatever captured around the corners.
This point is more angled towards scoring the game as I have seen though, I believe the current set of instructions have you score only within territories (which still doesn't make the first test true). 

String board5x5 = "  B  \n" +
	                      " B B \n" +
	                      "B W B\n" +
	                      " W W \n" +
	                      "  W  ";
@Test
	public void whiteCenter5x5BoardTest() {
		GoCounting gocounting = new GoCounting(board5x5);
		Set<Point> territory = new HashSet<>();
		territory.add(new Point(2, 3));
		assertEquals(Player.WHITE, gocounting.getTerritoryOwner(2, 3)); //should be NONE
		assertEquals(territory, gocounting.getTerritory(2, 3));
	}
and 
@Test
	public void openCorner5x5BoardTest() {
		GoCounting gocounting = new GoCounting(board5x5);
		
		Set<Point> territory = new HashSet<>();
		territory.add(new Point(0, 3));
		territory.add(new Point(0, 4));
		territory.add(new Point(1, 4));
		
		assertEquals(Player.NONE, gocounting.getTerritoryOwner(1, 4)); //should be BLACK
		assertEquals(territory, gocounting.getTerritory(1, 4));
	}

**Comment by FridaTveit** [comment]
Thanks for raising this @jhuiet! 🙂 However, deciding what the readmes and tests should be like is done in the [problem specifications repo](https://github.com/exercism/problem-specifications), and then we implement it here. We do that so that the tests are consistent across tracks.

So if you believe there is a problem with the go tests, please open an issue (and a PR if you want to fix it yourself) in the problem specifications repo. You can find the specification for the go exercise here: https://github.com/exercism/problem-specifications/tree/master/exercises/go-counting/.

I hope that makes sense, let me know if it doesn't 🙂

**Comment by FridaTveit** [comment]
I hope this makes sense @jhuiet! I'll close this issue for now, feel free to open an issue in problem specifications if you think there is a problem with the go exercise 🙂 And feel free to open a new issue here if you think there is something we should fix on this track 🙂
