### ISSUE TITLE
grep: conflicting flags

### ISSUE THREAD

**Issue by rstockbridge** [exercism/java#1491]
I just completed the grep exercise, and noticed that the tests didn't cover cases where flags conflict. E.g., what should happen in the following cases?
1. `-n` and `-l`
2. `-x` and `-v`

Some experimentation with grep shows that
1. `-n` takes precedence over `-l`
2. checks that the entire line does not match the pattern

The tests `oneFileNoMatchesVariousFlags()` and `multipleFilesNoMatchesVariousFlags()` contain the flags `-n`, `-l`, `-x`, and `-i`, but don't actually test the situations described above because there are no matches. 

I did make sure that my solution produces the behavior described above (http://exercism.io/submissions/74bcc15ff83b4a00aeb7a919e0f1158d) although certainly I may have missed other conflicting flag combinations.

It might be helpful to either include tests that indicate how to resolve conflicting flags, or the README should indicate that this level of detail is not necessary. What do you think?

**Comment by FridaTveit** [comment]
That's a good point, thanks for raising it @rstockbridge! 🙂 However, we have to make sure our tests and READMEs are the same as in [problem specifications](https://github.com/exercism/problem-specifications/) so that we stay consistent with the other tracks. This sounds like it's something that could benefit all tracks though, so if you wanted to you could raise this issue in problem specifications? 🙂

**Comment by rstockbridge** [comment]
Sure thing! Should I close this issue after opening it in problem specifications?

**Comment by FridaTveit** [comment]
That would be great yes 🙂 Thank you! 😃
