### ISSUE TITLE
scrabble-score: extension tasks require pre-set or submittable tests

### ISSUE THREAD

**Issue by zantetsuken88** [exercism/java#1497]
Having just attempted the scrabble-score exercise, I noted this was the first exercise on the track with suggested 'extension' tasks. 

The trouble is, knowing how to pass these criteria is very difficult to pin down without a a set of optional tests to verify your code is effective. 

Whilst it's possible to write your own tests, the track hasn't required this up until this point, there is no guidance for writing tests and it's not possible to submit any tests you've written, therefore whoever mentors your submission cannot review the validity or effectiveness of your tests. 

Either extension tasks should have pre-written (but optional) tests, or there needs to be a mechanism to submit tests.

**Comment by FridaTveit** [comment]
Hi @zantetsuken88, thanks for raising this issue! 🙂 The extension tasks are meant to be optional which is why they don't have as much guidance as other parts of the exercise. We could add a section to the README of the first exercise with extensions describing how to write tests if you think that would be useful?

As for submitting tests, that's not really something we can change on this track. I think opening an issue in https://github.com/exercism/exercism would probably be best 🙂 However bear in mind that there have been a lot of changes to exercism lately and people are very busy trying to make the new website with all its features work the way people want it to. So it might take some time before someone gets round to responding to your issue, and they might decide it's something we can't change at the moment. Not because people don't care but just because there's so much to do right now.

I hope that makes sense and sounds okay, let me know if not! 🙂

**Comment by FridaTveit** [comment]
I'll close this issue for now @zantetsuken88 since it's not something we can easily fix on this track. Feel free to ask us (on gitter or by opening a new issue) if you have any problems raising this in the correct repo or if you have any other questions! 🙂
