### ISSUE TITLE
Anagram exercise /main/java doesn't contain a .java file

### ISSUE THREAD

**Issue by xNS5** [exercism/java#1622]
The directory doesn't contain the .java file. I've checked, and all that's in the java GitHub repo is a .keep file.

**Comment by FridaTveit** [comment]
@xNS5 That's because anagram has difficulty 7. As explained in our [policies doc](https://github.com/exercism/java/blob/master/POLICIES.md#starter-implementations) only exercises with difficulty 4 or lower require starter implementation (which would be a .java file in /main/java). Any other exercises just require a .keep file in that folder so that git doesn't ignore those folders 🙂 Does that make sense? 🙂

**Comment by xNS5** [comment]
Noted! I'll take a look at the policies doc to make sure I don't miss anything else in the future. Thanks for the response!

**Comment by FridaTveit** [comment]
No problem! 🙂
