### ISSUE TITLE
Create stub files for all exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/java#1721]
We have decided to require all file-based tracks to provide stubs for their exercises.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.

The original discussion for this is at https://github.com/exercism/discussions/issues/238.

Therefore, we’d like this track to provide a stub file for each exercise.

- If this track already provides stub files for all exercises, please close this issue.
- If this track already has an open issue for creating stubs, then my apologies. Please close one as a duplicate.
- Otherwise, please respond to this issue with useful details about what needs to be done to complete this task in this track so that people who are not familiar with the track may easily contribute.

**Comment by lemoncurry** [comment]
At the moment, the track policy requires stubs for all exercises with difficulty < 5.

From the [original discussion](https://github.com/exercism/discussions/issues/238), we will have to do at least the following for all exercises with difficulty of 5 and above:
- add resp. stub, remove .keep


We need decisions on the following:
- whether the new stubs should be the same as for exercises with difficulty < 5
    - for all exercises with difficulty of 5 and above
    - for core exercises with difficulty of 5 and above, and standard text for the remaining
    - for no exercise with difficulty of 5 and above, instead use standard text
- standard texts for stubs to help getting started (which was already provided by us using the hints.md)
- change, remove or integrate the hints.md files (into stub standard text) to match the changes for the stub files we need a decision on; accordingly update the README.md

Personally I would suggest to use a standard text for all exercises with difficulty of 5 and above, and integrate the most important information from the hints.md into the stubs.
This way, we would still preserve the progressive nature of the stubs like before. The only difference is that the user no longer has to create the class file(s), and the hints.md would be integrated as comments in the stubs instead of in the README.md.

What do you think @exercism/java ?

**Comment by FridaTveit** [comment]
I think that sounds like a good plan 🙂 I think it's an important part of learning a new language to learn to create the classes and methods yourself, so I think ideally the later exercises should let the users do that themselves as much as possible 🙂

**Comment by lemoncurry** [comment]
Thank you @FridaTveit .
I might be able to work on the script this week, and maybe have a PR ready at the end of the week.
