### ISSUE TITLE
wrong HTML anchors into java installation page

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/java#1787]
I notice that in the page containing java installation instructions [here](https://exercism.io/tracks/java/installation) there is a problem with the links of OS sections.
I mean when you click Linux link for example ( same stuff happening with the others) a new page is opened and there isn't the correct HTML anchor on relative section.

I wanna propose a fix to this, but I don't understand where to find the source of this page, can someone help me ?

**Comment by jmrunkle** [comment]
The source is a markdown file here: https://github.com/exercism/java/blob/master/docs/INSTALLATION.md

I believe the intention is to open a link to the same page at the heading "Linux". Ironically, this works in the markdown view of the installation instructions, but fails on the webpage. Probably because the webpage does not automatically generate the anchor that the markdown generator or Github does.

I'm not actually sure if we should consider that a bug with our actual markdown content or a bug with the webpage generator (which really should auto-generate anchors for the heading tags).

**Comment by mirkoperillo** [comment]
I can confirm that the anchors are missing in the webpage.

I close the issue

**Comment by jmrunkle** [comment]
> I can confirm that the anchors are missing in the webpage.
> 
> I close the issue

@mirkoperillo - just curious, but did you open an issue against the website? Because there is still a real UI issue there that should be resolved?

**Comment by mirkoperillo** [comment]
@jmrunkle I don't know where to open this issue, if you know what repository is involved I can open the issue

**Comment by jmrunkle** [comment]
@mirkoperillo - start here: https://github.com/exercism/exercism/issues. They can move it if there is a more appropriate repo to put it in.

**Comment by mirkoperillo** [comment]
done https://github.com/exercism/exercism/issues/5268
