### ISSUE TITLE
Recruiting additional maintainers for Java

### ISSUE THREAD

**Issue by kytrinyx** [exercism/java#1789]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by pdmoore** [comment]
I'd like to help as a maintainer here. My exercism handle is pdmoore and I've been a mentor on the Java and C# tracks there. I've used Java since the beginning and have mostly kept up with its evolution - I still learn neat tricks from the solutions I review. My day job is technical trainer and coach. You know, extreme programming for those devs who think scrum is the only aspect of agile.

**Comment by sshine** [comment]
I'd like to participate in implementing concept exercises for the Java track as they're being made. The last time I wrote much Java was with Java 6, but I've had various C# jobs in the past 10 years. Since coming to Exercism in late-2018, I've come to realize that Java has been renewed so much that I enjoy it again.

I also have some responsibility for training new hires at my day job and a past as teacher, but my experience with curriculum design is limited, so I'd prefer to execute other people's designs on this track and design other tracks.

I've made minor contributions to half a dozen Exercism tracks, passively maintain a few and actively mentor/maintain one.

**Comment by mirkoperillo** [comment]
Hi I'm Mirko and I am interested in helping more in exercism.
My exercism account is **mirkoperillo**

I'm a professional Java developer since 12 years, you can find a lot of my daily work here on Github ( I work in a research foundation that produces Open Source software).
I have done some contributions on Java track in the last two Hacktoberfest events and between them.
I have a little experience as maintainer in one my little side-project [Resting](https://github.com/mirkoperillo/resting). 
I subscribed to Java track as a user to better understand the front-side of what I saw during the contributions.

I am interested in becoming a maintainer to have an experience with other more experienced maintainers and learn better how the game works.

**Comment by sshine** [comment]
@mirkoperillo: Sounds like an excellent plan. Learning about the role of open source software maintainer from someone more experienced than myself is one of the greater things that has happened in my career so far.

**Comment by msomji** [comment]
Hi my name is Maisam Somji ([msomji](https://exercism.io/profiles/msomji)) and I have been working on multiple different tracks in terms of practicing different exercises/learning new languages, mentoring others in completing their exercises as well as implementing new exercises for the tracks. With about 5 years of experience working with Java/Javascript/Typescript/Ruby I have been a huge proponent of using exercism.io as a tool to help others learn different languages and hone in on their skills.
I would love to become a maintainer in these tracks in order to continue to help grow this platform so that it can impact others in the same way that is has impacted me!

**Comment by jmrunkle** [comment]
I suppose I should mention explicitly on here that I would like to continue being a maintainer, but I'm not consistently available 2-3hr per week (so just helping out when I can). I am still adjusting to life as a parent (5-months into this new world), but I'm at least getting back to (at least) occasional maintenance of the Java repo.

**Comment by sshine** [comment]
Congratulations! So that's where you went. :-D

I started a new job, so I'm going to disappear for a while and gradually sink back.

**Comment by iHiD** [comment]
Congrats to both of you :)
