### ISSUE TITLE
AnagramTest.java has Zero Width Spaces

### ISSUE THREAD

**Issue by harmanhobbit** [exercism/java#1938]
All of the .containsExactlyInAnyOrder() calls have a Zero Width Space ([ZWSP]) before the parentheses so are actually .containsExactlyInAnyOrder[ZWSP](). This causes errors in some IDE such as Intellij Idea. An example is included below copied from the code hosted on github.

.containsExactlyInAnyOrder​("maters", "stream");

**Comment by mirkoperillo** [comment]
Hi @harmanhobbit thank you for your reporting.

I'm not a Intellij user, so currently I'm not able to reproduce quickly this bug.
I'll try to reproduce ASAP

@exercism/java anybody can help on this ?

**Comment by ericbalawejder** [comment]
There is a similar issue in #1843. I'm an IntelliJ Ultimate user and I'll look into these.

**Comment by ericbalawejder** [comment]
There is a zero width space character [ZWSP] in the two test files for anagram and nucleotide-count. It is visible after inspecting the hex view of each file.

<img width="683" alt="Screen Shot 2021-05-25 at 1 48 26 PM" src="https://user-images.githubusercontent.com/4513001/119597934-01fa3280-bdb0-11eb-91f1-b9ce5930cd69.png">

U+200B | ​ | 0xe2 0x80 0x8b | ZERO WIDTH SPACE

IntelliJ may be more sensitive to zero width space, as it's the only IDE that appears to be picking them up. When I delete the zwsp, the hex code is changed and the issue is resolved. Git does not seem to care about the change making it hard to spot in a code review. I'll change these files in their respective PRs. @mirkoperillo will this create a problem since the v2 track is frozen?

My best guess is that code was copy and pasted from the API through a browser. ZWSP lets your browser know when it’s okay to break a word onto a new line, without hyphenating it.

**Comment by mirkoperillo** [comment]
@ericbalawejder  I don't think. 
The current production code is frozen so it will not be impacted from the fix.
This fix will be "online" only when the v3 will be officially released ( in a few weeks I suppose)

Thanks @ericbalawejder for explaining how to identify this problem, I'm sure this know-how will be useful in the future.

**Comment by mirkoperillo** [comment]
Thank you to @ericbalawejder this issue (and another found in `nucleotide-count` exercise) has been fixed
