### ISSUE TITLE
gradle testCompile() fails

### ISSUE THREAD

**Issue by gutsHellsing** [exercism/java#1944]
first this is what i have on my machine

gradle:

Gradle 7.0

Build time: 2021-04-09 22:27:31 UTC
Revision: d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin: 1.4.31
Groovy: 3.0.7
Ant: Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM: 11.0.11 (Oracle Corporation 11.0.11+9)
OS: Windows 10 10.0 amd64

java:

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode)

now for the problem, everytime i try to run gradle test i get this:

FAILURE: Build failed with an exception.

    Where:
    Build file 'C:\Users\user\Dropbox\Studies\Projects\Exercism\java\Easy\pangram\build.gradle' line: 14

    What went wrong:
    A problem occurred evaluating root project 'pangram'.

    Could not find method testCompile() for arguments [junit:junit:4.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

BUILD FAILED in 1s

i did a bit of research and google and it's usually either a missing plugin or the maven repo but those should be fine in your provided file, i really need some help.

**Comment by mirkoperillo** [comment]
Hi @gutsHellsing this is known bug.
It has been already fixed in the main branch, but not currently in production because we are waiting for the official release of v3 platform (current v2 java track is freezed so cannot be updated).
The problem is the using of Gradle 7.x
You have two workarounds:
- downgrade gradle to the last 6.x version
- or follow this suggestion https://github.com/exercism/exercism/issues/5517#issuecomment-853100477

Let we know if you need other help

**Comment by gutsHellsing** [comment]
Hi @mirkoperillo, thanks for the fast respond.

also thanks for providing the workarounds, i can confirm that both work, and i choose to downgrade gradle for now.

i'm closing this issues for being solved.
