### ISSUE TITLE
Integer overflow risk in difference-of-squares

### ISSUE THREAD

**Issue by richarda23** [exercism/java#1957]
The difference-of-squares problem should raise the issue of integer overflow. Since the input and return value are both integers, and the calculation squares these inputs, in real production code there would be a risk of integer overflow. This is a big risk in production code so new Java developers should be aware of this!

Would suggest tests that validate input  to a value whose result can still be contained in an integer.So for example, a test that takes Integer.MAX as input should be rejected with an IllegalArgumentException.
Or 
  change the return type to long 
or
 at least mention this issue in community mentoring notes

Best wishes 
 Richard

**Comment by mirkoperillo** [comment]
@richarda23 if you are interested you can propose some new unit tests about

**Comment by richarda23** [comment]
Sure will do! It will be probably week after next before I get round to this.

**Comment by richarda23** [comment]
OK, looking into this it depends on how the solution is implemented. If it uses the formula the max allowed input values is 1023
as   1023 * (1024) * (2047)  is the largest that stays within Integer.Max_VALUE.
But if solver uses regular loop addition then the max allowed input value is much larger. 

So a test that asserts that an IllegalArgumentException is thrown if n > 1023 won't make much sense if they haven't used the formula.  

So would it be better /simpler to keep this as a discussion point in the community notes?

**Comment by ericbalawejder** [comment]
I follow the concern of overflow. Since the tests use small input (It looks like 100 is the largest value) it may not be too much of a concern. The point of squaring values while using the type `int` is valuable to make. As you pointed out, the input value that causes overflow depends upon the implementation. As you showed, using the series summation formula, the max is 1023. Using an accumulator variable in a loop, the max input appears to be 1860. There may be other implementations and I'm not sure how to test for that issue. Since this problem is from Project Euler, the problem is only asking for values from the first 100 natural numbers and the author chose the data type that made sense for that value.

**Comment by jmrunkle** [comment]
Since this discussion appears to be resolved I am closing this issue. You can open a PR for the community notes if that has not been done already.
