### ISSUE TITLE
Inaccurate compiler error description in 'foreach-loops' concepts

### ISSUE THREAD

**Issue by richarda23** [exercism/java#1966]
Reading about.md in concepts/arrays, 

```
char[] vowels = { 'a', 'e', 'i', 'o', 'u' };

for(char vowel:vowels) {
    vowels = 'Y';  // This would result in a compiler error
}
```
This only causes a compiler array as you are trying to assign a `char` to variable of type `char []`. This will always be a compiler error, not just in a foreach loop.

I tried modifying both values of arrays and setting vowels to a new char [] inside the loop, neither of which produced a compiler or runtime error (Java 11) . E.g.

```
 char[] vowels = { 'a', 'e', 'i', 'o', 'u' };
    for(char vowel:vowels) {
        vowels[0]= 'Z'; // NOT a compiler error
        vowels = new char []{'Y'}; // NOT a compiler error

    }
    System.err.println(Arrays.toString(vowels));

//
Y
``

So I don't think the current statement is correct, unless I'm misunderstanding it.

Richard

**Comment by ericbalawejder** [comment]
You are correct. This is a typo. Trying to assign a `char` to a `char[]` will result in a compiler error but I don't think that is the intention of the author in the post. I believe what they are trying to show is that you can not mutate the values of the `char[]` using the `for each` style loop. Only the variable in the loop changes, not the real array values. We would need an indexed loop to modify array elements.
```
char[] vowels = {'a', 'e', 'i', 'o', 'u'};

for (char vowel : vowels) {
    vowel = 'g';
}
System.out.println(vowels); // aeiou

for (int i = 0; i < vowels.length; i++) {
    vowels[i] = 'Y';
}
System.out.println(vowels); // YYYYY
```
I'm not sure what kind of compile error the author is trying to demonstrate. It's possible they are trying to mutate the array contents, but this leads to a `RuntimeException`.
```
for (char vowel : vowels) {
    vowels[vowel] = 'g';
}
```
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException`

Thank you for pointing this out.

**Comment by jmrunkle** [comment]
The problem has moved over to the `foreach-loop` concept, and the syntax is actually wrong:

```java
char[] vowels = ['a', 'e', 'i', 'o', 'u'];

for(char vowel: vowels) {
    vowels = ['Y'];  // This would result in a compiler error
}
```

Should be:

```java
char[] vowels = {'a', 'e', 'i', 'o', 'u'};

for(char vowel: vowels) {
    vowels = {'Y'};  // This would result in a compiler error
}
```

It technically results in a compiler error, but only because that particular syntax is not allowed for re-assigning arrays (only for initialization and assignment together). This version does not produce any compiler or runtime errors:

```java
char[] vowels = {'a', 'e', 'i', 'o', 'u'};

for(char vowel: vowels) {
    vowels = new char[] {'Y'};  // This does not result in a compiler error
}
```

I just used a REPL to check and it does **not** produce a compiler error. It still manages to iterate through the entire `vowels` array (as it was defined originally) and just leaves the vowels array assigned to the new array after the loop is processed (and during the processing).

Since the behavior is not what the authors were originally trying to warn about, I am just going to remove the line.

**Comment by jmrunkle** [comment]
Furthermore, it totally does let you modify elements of the array itself while looping through:

```java
char[] vowels = {'a', 'e', 'i', 'o', 'u'};

for (char vowel : vowels) {
  vowels[2] = 'y';
  System.out.println(vowel);
  System.out.println(vowels);
}
```

Prints:

```
a
aeyou
e
aeyou
y
aeyou
o
aeyou
u
aeyou
```

Anyway, just deleting it from the concept.
