### ISSUE TITLE
hello-world readme is incorrect

### ISSUE THREAD

**Issue by IAmLuisJ** [exercism/java#2114]
The [hello-world](https://exercism.org/tracks/java/exercises/hello-world) readme for the java track talks about changing the test, but the exercise only requires the user to change the string in the main java file.

Path to culprit MD file Exercism/java/java/exercises/practice/hello-world/.docs/instructions.append.md

It's good info, but not very relevant to this exercise. Perhaps it can be moved to a separate hello-world-unit-test exercise. Please let me know if you'd like I can try drafting up a more relevant instructions.append.md for this exercise.

**Comment by andrerfcsantos** [comment]
@IAmLuisJ You raise a good point. I think we should remove that bit of changing the tests from those instructions.

Are you still interested in working on this?

**Comment by c4p1t4n** [comment]
Hello, i'm interested in working  on this issue. Would be my first issue

**Comment by andrerfcsantos** [comment]
@c4p1t4n Thanks for the interest in contributing!

I assigned the issue to you.

Let me know if you have any additional questions while doing this :)

**Comment by c4p1t4n** [comment]
Thank you, I will work in  this issue in the weekend

**Comment by jcovington16** [comment]
Is this ticket still being worked on?

**Comment by saaagarsingh** [comment]
Hey Members. I've never contributed to open source projects. This issue seem a good first issue to start contributing.
can anyone please guide me on how should I proceed?

**Comment by andrerfcsantos** [comment]
@c4p1t4n Are you still interested in working on this?

**Comment by c4p1t4n** [comment]
hello guys I'm currently very busy with work but would be happy with someone else contributing to open source

**Comment by andrerfcsantos** [comment]
@c4p1t4n No worries, thanks for letting us know.

@jcovington16 Do you want to work on this?

**Comment by jcovington16** [comment]
Yes please.

**Comment by andrerfcsantos** [comment]
Go for it :)

**Comment by jcovington16** [comment]
Will do! Thank you.

**Comment by andrerfcsantos** [comment]
> Hey Members. I've never contributed to open source projects. This issue seem a good first issue to start contributing.
can anyone please guide me on how should I proceed?

@saaagarsingh Since @jcovington16 asked first, I assigned the issue to them, but feel free to contribute in other issues. [This video](https://www.youtube.com/watch?v=cysuuUtbC6E) explains how you can contribute to any open-source project. If you have further questions about this, feel free to drop them in [our gitter](https://gitter.im/exercism/support).

**Comment by IAmLuisJ** [comment]
Hello,

The primary objective would be to update the current hello-world readme so the instructions accurately reflect the exercise. 

Yes you are correct for the secondary objective, we should create a new exercise where the user is expected to write a unit test for the code. This would be helpful for developers new to unit testing.

**Comment by andrerfcsantos** [comment]
@jcovington16 Changing the tests is bad advice, because the student should never be required to do that in exercise. So the step 3 is the worst offender of those instructions, but in general I think we can remove the detail on how tests work because:

1. That's already explained in the [track docs](https://exercism.org/docs/tracks/java/tests), and the instructions of the hello world exercise already link to it. So this is kind of duplicated information. If we want to change anything in the test instructions, we should change it in the track docs, and not in the description of the hello world exercise.
2. In general, I feel the current instructions go into much detail, at the point of being overwhelming. This might discourage people to read the whole thing entirely. The whole process can be simplified to teach the student on how to run gradle, see the tests failing, change the solution and see the tests passing, but not explaining every detail and bit of output of the commands - they should be self-explanatory. If we feel like all this detail is necessary, we can do something similar to the [Unison track](https://exercism.org/docs/tracks/unison/tests), where there is a quick overview and a detailed walkthrough on how the tests work. As a student of the Unison track, I personally loved looking at the "quick overview" and doing things for myself with that just that little bit of guidance. The detailed overview was there just so if I had problems with quick overview or I wasn't fully understanding something. But to be clear, I don't think changes to the track docs should be part of this PR/issue, that can be a separate one. This PR should just focus on cleaning up the hello world description.
3. With v3 we now have the online editor which a lot of people use to start the tracks. This means that going into detail on how to test locally will only be significant for some users, and an online editor user might be even more confused by those instructions. Just having a link in the description for the track docs on testing is enough in my opinion.

So, to summarize, I think the tasks here are:

1. Remove everything related to the tests from the hello world exercise description, but keep a link to the track docs on testing on the Java track.
2. We should make sure that is clear for anyone that the instructions on the link only apply to local development. In the simple form, we should make sure that the link text contains something along the lines of "testing locally on the java track". If you feel like it, you can also make a new little section in the instructions of the hello world exercise just saying something brief along the lines "you can run the tests online using the online editor, but if you want to test locally, see this" with a link to the track docs on testing.
3. (Optional) Changing the track docs on testing to include more detail and separating them into "quick overview" and "detailed walkthrough". I personally think this is a nice to have, but not totally essential right now. If you want to also do this together with the changes to the exercise description, I'll make sure to adjust the PR size, however, I'd prefer this to be a separate issue/PR.

**Comment by jcovington16** [comment]
@andrerfcsantos I completely agree that changing tests is the wrong thing to do. I've always written my tests first and then write my code to ensure the test passes. I always look for different edge cases that I should test for while creating my tests.

Thank you very much for the thorough explanation on what needs to be done. I already forked and branched off of main, so I will go ahead and conduct the necessary changes now.

**Comment by jcovington16** [comment]
@andrerfcsantos I was having issues installing configlet. Is this a make or break pertaining the contents of the PR I created? Or is there a work around? If not then I will take another stab at going the configlet route. I know it makes things a lot easier for you guys, but this somewhat of a small tasks I didn't think it would cause any conflicts. I know you guys don't like to merge. I'm just trying to make sure I'm following the guidelines properly.

**Comment by andrerfcsantos** [comment]
@jcovington16 This change doesn't require configlet at all. configlet is only needed mainly when syncing problem descriptions and tests with the problem specification repo. But feel free to open an issue in https://github.com/exercism/configlet with the issue you are having installing it.

**Comment by andrerfcsantos** [comment]
Closing the issue since this is now fixed by #2135
