### ISSUE TITLE
Two Fer: test emptyStringIsNotTheSameAsNull

### ISSUE THREAD

**Issue by bobahop** [exercism/java#2128]
It's a bit confusing that the test named `emptyStringIsNotTheSameAsNull` actually expects that an empty string _is_ the same as null. If null, we should get "One for you, one for me.". If an empty string is _not_ the same as null, then the greeting should be "One for , one for me." So, perhaps either the test should be renamed or the expectation should be fixed.

```java

/* Track specific */
@Test
public void emptyStringIsNotTheSameAsNull() {
    assertThat(twofer.twofer("")).isEqualTo("One for you, one for me.");
}
```

**Comment by andrerfcsantos** [comment]
Thanks for raising this!

In this case, the test should be renamed to something like `emptyStringIsTreatedTheSameAsNull`.

**Comment by kotp** [comment]
We should be careful, though. If `Null` is the result of not giving any name at all, we should still use `you` if no name is given, but we should honor the name given if the name given is `Null`.  According to the README, it states:  "Given a name, return a string with the message:"  If an empty string is given, then accept that as the name given.  We are not the name experts we think we are, hence it is why we ask for a name.  The giver is the expert, and if they know their name is `""` then who are we to argue, especially since we are the ones that asked (if we knew, would we need to ask?).

**Comment by bobahop** [comment]
I tend to agree with Victor on this one, as I believe in at least one other language the empty string is accepted as is and is not expected to be morphed into "you." I'll see if I can find it (if it matters...)

**Comment by bobahop** [comment]
Okay, this was "fixed" about [eight days ago](https://github.com/exercism/java/commit/e3594e5341ac4decf8c13d4f994234e443e08022). It was actually Java in which I saw this before, where an empty string was not treated as null. I believe this "fix" was misguided.

**Comment by bobahop** [comment]
I'm okay with submitting a PR for whichever the maintainers think is the right way to handle this.

**Comment by andrerfcsantos** [comment]
@bobahop The issue with that approach is that in the instructions, the table shows that an "empty" name must be converted to "you" and that was the reason for that PR in the first place. Since the table doesn't really mention `Null`, it makes sense to consider the empty string as "you".

I see 2 alternatives to this:

1. We remove the test for the empty string completely and just have a test for `null`. This is the approach Python takes, where they only test for `None`. The specs in problem specifications also have a test for `null` but none for the empty string, so this would make our tests align with problem specifications. This would also mean not taking a strong stance on whether an empty string is a "no name". I prefer this approach.
2. If we want to keep the difference, since we can't change the table from problem specs for the description of the exercise, we should add a clarification to `instructions.appends.md` along with reverting the tests. I don't really like this because this is an easy exercise very early in the track and I don't see much value in having these edge cases, but I'm willing to be convinced otherwise.

**Comment by bobahop** [comment]
Actually, the instructions say to replace a "missing" name with "you". It could be said that null is a missing value, and empty is not missing, it's a value, just that it is empty.

I like your preferred option 1, so I'll go ahead and put a PR in for that.

**Comment by kotp** [comment]
So far, Ruby has kept it so if no argument is given, then "you" is used, but if any argument is given, it is treated as the name and produced in the output (visible or not), including `nil` or `""` or `42` or `"\v"`, etc.
