### ISSUE TITLE
Hacktoberfest tag

### ISSUE THREAD

**Issue by aldotele** [exercism/java#2506]
Hi there, I think it would be a good idea to mark this repository as eligible for the [Hacktoberfest](https://hacktoberfest.com/) .
Adding the **hacktoberfest** tag should do the trick.

**Comment by sanderploegsma** [comment]
That's an interesting suggestion, thanks! I'd be willing to mark this repository as participating, but I'm not able to update the topics on the repository. Perhaps @ErikSchierboom  is able to help out.

Also, leaving this here since it contains more information about participating as maintainers: https://hacktoberfest.com/participation/#maintainers

**Comment by ErikSchierboom** [comment]
Done

hacktoberfest
