### ISSUE TITLE
list-ops: estimate difficulty and move to appropriate position within track

### ISSUE THREAD

**Issue by stkent** [exercism/java#325]
The exercise `list-ops` was added after we'd already re-ordered the track. By default, new exercises are scored with difficulty 1 and located at the end of the track. We should use this issue to discuss and determine an estimated difficulty for `list-ops`, then submit an associated PR that moves `list-ops` to the appropriate position within the track based on that difficulty.

**Comment by FridaTveit** [comment]
Without any starter implementation I found list-ops very hard because it was a challenge trying to reverse engineer the signatures. So as it is I would give it a difficulty of 9 or 10. I don't think figuring out what the signatures are should be the challenging part of the exercise though. So I think the exercise could be improved by adding a starter implementation and possibly explaining what the different functions are meant to do in the README (or adding links to explanations). If we did that then I think the exercise wouldn't be so difficult, maybe 7?

**Comment by stkent** [comment]
Closed by #670.
