### ISSUE TITLE
binary-search-tree: extract initialization and rename test class

### ISSUE THREAD

**Issue by jtigger** [exercism/java#376]
In the `binary-search-tree` exercise, the test class is named `BSTTest` and the target class name is `BST`.  For better or for worse, idiomatic Java avoids abbreviations.  Also, each test method creates its own instance of `BST`.  Unfortunately, [Shalloway's Law](http://www.netobjectives.com/blogs/shalloways-law-and-shalloways-principle) applies.

Please:
1. Rename the test suite to a more descriptive name.
1. Rename the target class to a congruent name (ideally, the name of the test suite is the name of the class with a `Test` suffix).
1. Extract construction of the subject under test in [`setUp()`](http://junit.sourceforge.net/javadoc/org/junit/Before.html).

**Comment by morrme** [comment]
I would like to help, with a little guidance if possible.

**Comment by FridaTveit** [comment]
Great, go for it! :) If there's anything you need help with you can just comment on this issue and we can try to help :)

**Comment by morrme** [comment]
@FridaTveit Thank you. 
From what I see, the two files involved are:
/exercises/binary-search-tree/src/test/java/BSTTest.java
and
/exercises/binary-search-tree/src/example/java/BST.java

Is this correct? 

I am looking at other files to get an idea of a convention for possible test and class names. Do you have a preference or suggestion?

**Comment by FridaTveit** [comment]
Yup, those are the correct files :) The convention for class names in java is to start with a capital letter, use [camelCase](https://en.wikipedia.org/wiki/Camel_case) and avoid abbreviations. So I would suggest BinarySearchTree.java and BinarySearchTreeTest.java :)

**Comment by delbertlegg** [comment]
I'll take this on!

**Comment by FridaTveit** [comment]
Great! Thanks @delbertlegg! :)

No, from our [POLICIES doc](https://github.com/exercism/java/blob/master/POLICIES.md#starter-implementations) you can see that we only require stubs for the first 20 exercises on the track (i.e. the first 20 exercises listed in `config.json`). This exercises comes later in the track so there shouldn't be any starter implementation :) I hope that makes sense, let me know if you have any questions :)

**Comment by delbertlegg** [comment]
@FridaTveit Ah, okay...just so I understand completely, there's the test class, and then there's an implemented BST class in the reference folder. What's the purpose of that class? Is the user expected to create a new class in the main/java folder?

**Comment by FridaTveit** [comment]
The user will only be provided with the test, not the reference solution. So yes, they're expected to implement their solution in `main/java`, where we currently either have a `.keep` file or a starter implementation, depending on how early in the track the exercise is.

The reference solution is just for contributors. When you make a PR the travis build will run all the tests against the reference solution (removing all the `@Ignore` annotations so that all the tests run) and check that they pass. That way we know that the tests are correct in that it's possible to write an example solution which passes all the tests. And it makes it easy to see if any change has broken the tests :) The [contributing guide](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#the-problem-submodules) also explains how the exercise modules work. Does that make sense? :)

**Comment by delbertlegg** [comment]
RTFM aye! :) Thanks for the explanation. Working on the fix now.
