### ISSUE TITLE
all-your-base: some questions

### ISSUE THREAD

**Issue by rstockbridge** [exercism/java#519]
I just did the all-your-base exercise, and a couple things occurred to me that I'd like clarification on:

1. The test `testFirstBaseIsOne` passes two invalid arguments, but expects an error message for the first one. This forces a certain order of error checking in the implementation. Is that expected/desired? Would the test be clearer if just the first input was invalid?

2. Would it make sense for the input and output to be formatted as a list rather than an array? As part of the calculation the size of the result is typically unknown ahead of time. I stored my results as a list and then converted to an array - could this be simpler? (Of course, using a list could signal misleadingly to the user that the output size is dynamic.) What do people think?

**Comment by FridaTveit** [comment]
Thanks for your suggestions! :)

1. I agree that enforcing a certain order of error checking is unnecessary. This is a problem in the [canonical data](https://github.com/exercism/x-common/blob/master/exercises/all-your-base/canonical-data.json) as well, I don't know if it's worth changing it there or whether we should just change it for this track?

2. The example implementation uses arrays all the way through so it would be a bit simpler to keep it as an array. But as you can convert from an array to a list and vice versa, I don't particularly mind which one we go for.

Thoughts @exercism/java?

**Comment by stkent** [comment]
1. I think it's worth raising the question in x-common, for sure :)

2. Agreed, the appropriateness of the public API should take precedence over the internal implementation details; implementors can choose `List` types for all internal representation if they prefer.

**Comment by stkent** [comment]
Ah, on a closer look, the _data_ is the same in x-common, but x-common doesn't say anything about what the exception language should be, so we have some track leeway there too.

**Comment by FridaTveit** [comment]
From looking at the test data in x-common, it looks like no matter what we change the input digits to be in `testFirstBaseIsOne` it will conflict with some other test. If the input digits are empty, the result could be `null` because of that. If the input digits aren't empty then the output could be `null` because the input digits aren't stricly less than the base, or they're all 0. So it doesn't look like changing the test data would do much good.

I would suggest changing the error message to something more general, e.g. "Invalid input" or just `IllegalArgumentException` without a message. Thoughts @rstockbridge, @stkent?

**Comment by stkent** [comment]
:+1: for generalizing the error language so that it is the same in both cases. I'll create an actionable issue.

**Comment by stkent** [comment]
u-turn alert! I went to write that new issue, and I tried to imagine myself using an existing API that throws exceptions, and figure out whether or not I'd be surprised if multiple invalid inputs results in only the first exception being raised, and I think... I wouldn't be surprised. I'm looking for some references here to see what else is out there.

**Comment by stkent** [comment]
Ok, I think the best solution here is to leave everything as-is. Here are some of my random thoughts:

- If we use a special error message for this particular case, we're increasing the complexity of the required solution for little gain;
- Validating the first input first makes sense; maybe we should change the test order (here and in x-common) so that users pass the first input validation test before any validation involving the second input. That would at least guide users the right way;
- In tracks that choose to allow leading zeroes, presumably `1, [0]` would be considered a valid pair of inputs representing the number 0? I'll ask this question in x-common.

**Comment by stkent** [comment]
Data point: xcsharp bakes in implicit ordering:

https://github.com/exercism/xcsharp/blob/master/exercises/all-your-base/Example.cs#L9-L11

but doesn't validate the thrown exception message.

**Comment by stkent** [comment]
Oh, look at that!

https://github.com/exercism/xcsharp/commit/f8fb9cd73e476aacf8690f1afd58c6026b139d43

**Comment by stkent** [comment]
Ok, pausing this until we hear back from the xcsharp crew ⛵️

**Comment by rstockbridge** [comment]
Thanks for digging into this @stkent!

**Comment by stkent** [comment]
Ok, test cases are reordered in x-common which means this issue should be handled much better after we update to v1.1.0 of the canonical tests. Let's make that a precondition for closing this issue.
