### ISSUE TITLE
largest-series-product: create and/or validate starter implementations

### ISSUE THREAD

**Issue by stkent** [exercism/java#549]
Ref.: https://github.com/exercism/xjava/blob/master/POLICIES.md#starter-implementations

This exercise is currently one of the second ten exercises in the track. Please review the exercise files and create and/or update the starter implementation according to the guidelines provided in the link above.

**Comment by delbertlegg** [comment]
@FridaTveit I'll take this on.

**Comment by delbertlegg** [comment]
@FridaTveit Question for you...I was going through the tests to ensure that I added the required stubs and understood the problem statement and noticed that expected behavior for passing 0 in `calculateLargestProductForSeriesLength() ` is expected to return 1, although it isn't specified in the README. Should we say that in the README or just let the user infer that via the tests? Thanks!

**Comment by FridaTveit** [comment]
I think it's fine to let the user infer that via the tests :) Thanks for asking though! :)

**Comment by delbertlegg** [comment]
Good deal, thanks!
