### ISSUE TITLE
kindergarten-garden: incorrect unit tests

### ISSUE THREAD

**Issue by chuckwondo** [exercism/java#659]
The following unit tests are incorrect:

- `customStudentGardenFirstStudent`
- `customStudentGardenSecondStudent`
- `customStudentGardenThirdStudent`
- `customStudentGardenFourthStudent`

Each one specifies a student name that is not the name in the position indicated by the ordinal value in the test method name.

For example, in `customStudentGardentFirstStudent`, we have the following lines:

```java
String[] studentArray = {"Samantha", "Patricia", "Xander", "Roger"};
String student = "Patricia";
String plants = "VCRRGVRG\nRVGCCGCV";
List<Plant> expected = Arrays.asList(Plant.VIOLETS, Plant.CLOVER, Plant.RADISHES, Plant.VIOLETS);
```

The value of `student` should be `Samantha`, not `Patricia`, since `Samantha` is the first student. This can be further verified by cross referencing the value of `plants` to `expected` to see that indeed the expected answer is for the student at index `0` (the "first" student), who is `Samantha`, not `Patricia`.

The case is similar for the other 3 tests.

**Comment by FridaTveit** [comment]
Thanks for finding this @chuckwondo! I'll fix it and submit a PR :)

**Comment by FridaTveit** [comment]
After looking at this more closely, it's not actually a bug. The students are in alphabetical order which is why Patricia is before Samantha. It does say so in the [description](https://github.com/exercism/x-common/blob/master/exercises/kindergarten-garden/description.md):
>The children are assigned cups in alphabetical order.

 But I agree that it's easy to miss. Maybe changing the test names to `customStudentGardenInNonAlphabeticalOrderFirstStudent` or `customStudentGardenFirstStudentInAlphabeticalOrder`? Do you think that would help @chuckwondo?

**Comment by chuckwondo** [comment]
Ah, yes. Now it makes sense. Yes, perhaps a name change would help. I like your second suggested name.

**Comment by FridaTveit** [comment]
Great, I'll change it to that then :)
