### ISSUE TITLE
Mention rebases in README.md?

### ISSUE THREAD

**Issue by Smarticles101** [exercism/java#676]
I was wondering if we should mention the magic of doing a `git rebase` in the README file. I have noticed some pull requests where people frequently merge the original repository into their fork, which leads to a dirty commit history.

**Comment by stkent** [comment]
Could be a good idea to describe them as preferred. I wouldn't want to deter a potential contributor because of a git-related requirement, especially since we have the squash option when merging pull requests. I'd also suggest maybe adding this note in the CONTRIBUTING file (we should maybe link to that file from the README also). Thoughts, @Smarticles101?

**Comment by Smarticles101** [comment]
I agree. While we are talking about it, should we move the contributing guide from the README file to the CONTRIBUTING file?

**Comment by stkent** [comment]
Seems appropriate, as long as it's called out clearly in the README as described above!

**Comment by Smarticles101** [comment]
Closed by #680
