### ISSUE TITLE
HINTS.md for exercises with position 21 or greater?

### ISSUE THREAD

**Issue by dawcars** [exercism/java#687]
I have noticed that some exercises with position 21 or greater do not have HINTS.md. The wording of the POLICIES.md section on 'starter implementations' for exercises 21+ is a little unclear. Is it a requirement that HINTS.md should be there if the implementation stub is not there or is this only for exercises with complicated method signatures? Some exercises have neither HINTS.md or implementation stub and I just wanted clarification on how it should be.

**Comment by Smarticles101** [comment]
The POLICIES.md doc is in the process of being updated. (See #685). I think that the idea is after exercise 21, users should be pretty familiar with everything and should be able to write the solution completely by themselves. The HINTS.md file in an exercise should be used for any "interesting" aspects. Looking at these files in different exercises can help give you an idea of what they are for.

**Comment by dawcars** [comment]
Thanks @Smarticles101. So, if I am building an exercise, do I only add a HINTS.md file if there is something in particular I think would help the user or is this something that definitely has to be there if the stub is not there?

**Comment by stkent** [comment]
It's fine for there to be both no stubs and no hints :) Thanks for checking!

**Comment by dawcars** [comment]
Thanks @stkent. That's good to know.

**Comment by stkent** [comment]
No problem! If you're interested, the available 'template' files are listed in the [Exercism docs](https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/exercise-readmes.md) repo, though in most cases you'd need to actually inspect the source code of [trackler](https://github.com/exercism/trackler) (which assembles exercise READMEs) to determine whether any given template file is required or optional. (In general, I believe it's safe to assume optional unless otherwise noted!)

**Comment by dawcars** [comment]
Those links are really helpful. I did not know about trackler. Thanks @stkent

**Comment by Smarticles101** [comment]
Looks like this is cleared up now
