### ISSUE TITLE
Preparing for hacktoberfest!

### ISSUE THREAD

**Issue by Smarticles101** [exercism/java#766]
Ref. exercism/discussions#190

Hacktoberfest is about a month away! This issue is for thoughts regarding the java track for hacktoberfest.

**Comment by Smarticles101** [comment]
One idea that came to my head, is creating a ticket to make test suite generators

**Comment by stkent** [comment]
My sense is that there is a trend within Exercism to move away from the absolute agreement with canonical data that a test suite generator would produce (in favor of my idiomatic implementations). Don't get me wrong; I love canonical data and very rarely implement an exercise for which it doesn't exist (because I think it improves the quality so much), but writing a _good_ generator would be v. v. hard.

**Comment by FridaTveit** [comment]
I added the `hacktoberfest` label to all our `good first patch` issues. Hopefully that'll make it easier for people to contribute :)

**Comment by stkent** [comment]
We came, we prepped, we conquered! Many thanks @FridaTveit for opening and shepherding all those issues! 👏
